name: swingo
description: Swingo Native Mobile Application
author: Swingo
homepage: https://goswingo.com

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # Axios like library to make http requests
  dio: ^2.1.3
  url_launcher: ^5.0.2
  # flare_flutter:
  #   git:
  #     url: git://github.com/2d-inc/Flare-Flutter.git
  #     ref: 4aebb0ff5b98c7bcf2183c6bac8226cc7ddf5402
  #     path: flare_flutter
  auto_size_text: ^1.1.2
  intl: any
  font_awesome_flutter: any
  provider: ^3.0.0
  http: ^0.12.0+2
  shared_preferences: ^0.4.3
  adhara_socket_io: ^0.1.11
  webview_flutter: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  ios: true
  android: true
  image_path: "assets/launcher/app_icon.png"
  adaptive_icon_background: "#f9b130"
  adaptive_icon_foregrund: "assets/launcher/app_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/flare/
    - assets/2.0x/wallet.png
    - assets/slanted_menu.png
    - assets/wallet.png
    - assets/walletColor.png
    - assets/style_sphinx/
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/images/chat-background.jpg
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/Muli-Regular.ttf
        - asset: assets/fonts/Muli-Bold.ttf
